cars=["benz","bmw","audi","maruti",1,2]
print(cars[3])
demo=["f","u","t","u","r","a"]
print(demo[1:5])
demo1=['a','b','c','d','e','f','g']
print(demo1[:6])
print(demo1[:-3])
print(demo1[:])
demo1[1]="m"
print(demo1)
demo1.extend(['p','q','r','s','t','u'])
print(demo1)
demo1.append('x')
print(demo1)
print(len(demo1))
add=[1,2,3,4,5,6]
print(add+[7,8,9])
print(add*3)
num=[2,4,5,9,10]
num.insert(3,6)
print(num)
num[3:3]=[6,7,8]
print(num)
day=['t','o','m','m','o','r','r','o','w']
#pop
print(day.pop())
print(day)
#remove
day.remove('o')
print(day)
#clear
day.clear()
print(day)

local=['c','o','l','l','e','g','e']
local[3:5]=[]
print(local)
local[3:6]=[]
print(local)
